### ISSUE TITLE
http://ix.cs.uoregon.edu/~alih/compact-transformers/checkpoints/finetuned/ cct_14_7x2_384_imagenet.pth

### ISSUE THREAD

**Issue by yzxyzxyzxyzxyzx** [stevenwalton/SCS-CCT#1]
hi，i need the image of cct_14_384,but the link gave me the information of 404 httperror when i open it.so how can i get it?

**Comment by stevenwalton** [comment]
I think you're in the wrong project? You probably want to be [here](https://github.com/SHI-Labs/Compact-Transformers) (see README.

This project was just a fun experiment on top of CCT testing Sharpened Cosine Simularity (see [Brandon Rohrer](https://github.com/brohrer/sharpened-cosine-similarity)'s project)

**Comment by yzxyzxyzxyzxyzx** [comment]
okok，i find what i need,thankyou
